package com.kone.kitms;

import jakarta.annotation.Generated;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * KITMS JHipster 생성 어노테이션
 * 
 * 이 어노테이션은 JHipster 프레임워크에 의해 자동 생성된 클래스임을 표시합니다:
 * - JHipster 8.1.0 버전으로 생성됨
 * - 소스 코드 레벨에서만 유지되는 어노테이션
 * - 타입(클래스)에만 적용 가능
 * - 코드 생성 도구에 의한 자동 생성 표시
 * 
 * @author JHipster
 * @version 8.1.0
 * @since 2024
 */
@Generated(value = "JHipster", comments = "Generated by JHipster 8.1.0")
@Retention(RetentionPolicy.SOURCE)
@Target({ ElementType.TYPE })
public @interface GeneratedByJHipster {
}
